[package]
name = "ton-indexer"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[lib]
name = "ton_indexer_lib"
path = "src/lib.rs"

[[bin]]
name = "ton_indexer"
path = "src/main.rs"
required-features = ["binary"]

[[bench]]
name = "block_parse"
harness = false

[workspace]
members = ["indexer-lib", "node-indexer"]

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
base64 = "0.13"
config = "0.11"
clap = { version = "3.0.0-beta.2", optional = true }
dashmap = "4.0"
external-ip = "4.1"
futures = "0.3"
hex = "0.4"
log = "0.4"
log4rs = { version = "1.0", optional = true }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.8", optional = true }
tokio = { version = "1.6", features = ["sync"] }
thiserror = "*"

ton_abi = { git = "https://github.com/tonlabs/ton-labs-abi.git" }
ton_api = { git = "https://github.com/broxus/ton-labs-tl.git", package = "ton_api", branch = "original" }
adnl = { git = "https://github.com/broxus/ton-labs-adnl", default-features = false, features = ["node"] }
dht = { git = "https://github.com/broxus/ton-labs-dht.git", branch = "old-raptorq" }
rldp = { git = "https://github.com/broxus/ton-labs-rldp.git", branch = "old-raptorq" }
overlay = { git = "https://github.com/broxus/ton-labs-overlay.git", branch = "old-raptorq" }
ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
indexer-lib = { path = "./indexer-lib" }

[features]
binary = ["clap", "log4rs", "serde_yaml", "tokio/rt-multi-thread", "tokio/macros"]
