[package]
name = "ton-indexer"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[lib]
name = "ton_indexer_lib"
path = "src/lib.rs"

[[bin]]
name = "ton_indexer"
path = "src/main.rs"
required-features = ["binary"]

[[bench]]
name = "block_parse"
harness = false

[workspace]
members = ["indexer-lib", "node-indexer", "node-indexer-test"]

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
base64 = "0.13"
bincode = "1.3"
config = "0.11"
clap = { version = "3.0.0-beta.2", optional = true }
dashmap = "4.0"
ed25519-dalek = "1.0"
external-ip = "4.1"
futures = "0.3"
hex = "0.4"
log = "0.4"
log4rs = { version = "1.0", optional = true }
parking_lot = "0.11"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.8", optional = true }
sled = "0.34"
tokio = { version = "1.6", features = ["sync", "fs"] }
thiserror = "*"

ton_abi = { git = "https://github.com/tonlabs/ton-labs-abi" }
ton_api = { git = "https://github.com/broxus/ton-labs-tl.git", package = "ton_api", branch = "original", default-features = false }
tiny-adnl = { git = "https://github.com/broxus/tiny-adnl.git" }
ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
indexer-lib = { path = "./indexer-lib" }
serde_json = "1.0"

[features]
binary = ["clap", "log4rs", "serde_json", "serde_yaml", "tokio/rt-multi-thread", "tokio/macros"]

#[profile.release]
#debug = 1