[package]
name = "ton-indexer"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2021"
rust-version = "1.56"

[workspace]
members = ["ton-indexer-alloc", "ton-indexer-profile"]

[[example]]
name = "simple_node"
path = "examples/simple_node.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.13"
bincode = "1.3"
bytes = "1.1.0"
crc = "1.8"
dashmap = "4.0"
fdlimit = "0.2.1"
futures = "0.3"
hex = "0.4"
itertools = "0.10.1"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
num_cpus = "1.13.0"
parking_lot = "0.11"
pin-project-lite = "0.2"
rand = "0.8"
rlimit = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
smallvec = { version = "1.6.1", features = ["serde", "write", "union"] }
sysinfo = { version = "0.20.1", default-features = false }
thiserror = "*"
tokio = { version = "1.6", features = ["sync", "fs", "rt-multi-thread"] }
lru_time_cache = "0.11.11"

ed25519-dalek = { git = "https://github.com/broxus/ed25519-dalek.git" }
rocksdb = { git = "https://github.com/broxus/rust-rocksdb.git", features = ["multi-threaded-cf", "lz4", "jemalloc"], default-features = false }

ton_api = { git = "https://github.com/broxus/ton-labs-tl.git", package = "ton_api", default-features = false }
tiny-adnl = { git = "https://github.com/broxus/tiny-adnl.git" }
ton_block = { git = "https://github.com/broxus/ton-labs-block.git" }
ton_types = { git = "https://github.com/broxus/ton-labs-types.git" }

nekoton-utils = { git = "https://github.com/broxus/nekoton.git" }

ton-indexer-alloc = { path = "ton-indexer-alloc" }
ton-indexer-profile = { path = "ton-indexer-profile" }

[dev-dependencies]
argh = "0.1"
config = { version = "0.11", default-features = false, features = ["yaml"] }
external-ip = "4.1"
log4rs = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "1.6", features = ["sync", "fs", "rt-multi-thread", "macros"] }

[features]
default = []
asm = ["sha2/asm", "ed25519-dalek/asm", "ton_types/asm", "ton_block/asm", "tiny-adnl/asm"]
profile = ["ton-indexer-profile/active"]
