[package]
name = "ton-indexer"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[lib]
name = "ton_indexer_lib"
path = "src/lib.rs"

[[bin]]
name = "ton_indexer"
path = "src/main.rs"
required-features = ["binary"]

[dependencies]
anyhow = "1.0"
config = "0.11"
clap = { version = "3.0.0-beta.2", optional = true }
log4rs = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.8", optional = true }
tokio = { version = "1.6", features = ["sync"] }

[features]
binary = ["clap", "log4rs", "serde_yaml", "tokio/rt-multi-thread", "tokio/macros"]
