[workspace]
members = ["node-indexer", "shared-deps"]
[package]
name = "ton-indexer"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[dependencies]

#[lib]
#name = "ton_indexer_lib"
#path = "src/lib.rs"

#[[bin]]
#name = "ton_indexer"
#path = "src/main.rs"
#required-features = ["binary"]
#
#[dependencies]
#
#[features]
#binary = ["clap", "log4rs", "serde_yaml", "tokio/rt-multi-thread", "tokio/macros"]
