[package]
name = "ton-indexer"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[[example]]
name = "simple_node"
path = "examples/simple_node.rs"

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
base64 = "0.13"
bincode = "1.3"
crc = "1.8"
dashmap = "4.0"
ed25519-dalek = "1.0"
futures = "0.3"
hex = "0.4"
num-traits = "0.2"
log = "0.4"
libc = "0.2"
num_cpus = "1.13.0"
parking_lot = "0.11"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
smallvec = { version = "1.6.1", features = ["serde", "write", "union"] }
tokio = { version = "1.6", features = ["sync", "fs"] }
thiserror = "*"

rocksdb = { version = "0.17.0", features = ["multi-threaded-cf"] }

ton_api = { git = "https://github.com/broxus/ton-labs-tl.git", package = "ton_api", default-features = false }
tiny-adnl = { git = "https://github.com/broxus/tiny-adnl.git" }
ton_block = { git = "https://github.com/broxus/ton-labs-block.git" }
ton_types = { git = "https://github.com/broxus/ton-labs-types.git" }

nekoton-utils = { git = "https://github.com/broxus/nekoton.git" }

[dev-dependencies]
clap = "3.0.0-beta.2"
config = "0.11"
external-ip = "4.1"
log4rs = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "1.6", features = ["sync", "fs", "rt-multi-thread", "macros"] }
